import { MissileTypes } from './Missiles'
import UnitProfile, { UnitTypes } from './UnitProfile'
import { UnitTraits } from './UnitTrait'

const UnitProfiles: Record<string, UnitProfile> = {
  WarriorsHeavyInfantry: UnitProfile.fromObject({
    type: UnitTypes.Warriors,
    name: 'Heavy Infantry',
    points: 21,
    combatDice: 12,
    shootingDice: 0,
    armour: 3,
    stamina: 4,
    traitsLimit: 5,
    options: [
      { id: 1, name: 'Reduce Armour to 2', points: -5, modifiers: { armour: -1 } },
      { id: 2, name: 'Increase Armour to 4', points: 5, modifiers: { armour: 1 } },
    ],
    availableTraits: [
      { trait: UnitTraits.Amphibious, points: 1 },
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.Big, points: 0 },
      { trait: UnitTraits.Brittle, points: -1 },
      { trait: UnitTraits.Brutal, points: 16 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Fearsome, points: 3 },
      { trait: UnitTraits.Impetuous, points: 0 },
      { trait: UnitTraits.Pikes, points: 2 },
      { trait: UnitTraits.Relentless, points: 2 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.SpearsAsTribute, points: 3 },
      { trait: UnitTraits.Steadfast, points: 1 },
    ],
  }),
  WarriorsHeavyInfantryWithMissiles: UnitProfile.fromObject({
    type: UnitTypes.Warriors,
    name: 'Heavy Infantry with Missiles',
    points: 21,
    combatDice: 10,
    shootingDice: 5,
    armour: 3,
    stamina: 4,
    traitsLimit: 5,
    options: [
      { id: 1, name: 'Reduce Armour to 2', points: -5, modifiers: { armour: -1 } },
      { id: 2, name: 'Increase Armour to 4', points: 5, modifiers: { armour: 1 } },
      {
        id: 3,
        name: 'Exchange Javelin for Short Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 4,
        name: 'Exchange Javelin for Bow',
        points: 2,
        modifiers: { missileType: MissileTypes.BowOrMountedElfBow },
      },
      {
        id: 5,
        name: 'Exchange Javelin for Elf Bow/ Long Bow/ Crossbow:',
        points: 3,
        modifiers: { missileType: MissileTypes.ElfBowOrCrossbowOrLongbow },
      },
    ],
    missileType: MissileTypes.Javelins,
    availableTraits: [
      { trait: UnitTraits.Amphibious, points: 1 },
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.Big, points: 0 },
      { trait: UnitTraits.Brittle, points: -1 },
      { trait: UnitTraits.Brutal, points: 14 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Fearsome, points: 3 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Impetuous, points: 0 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Pikes, points: 2 },
      { trait: UnitTraits.Relentless, points: 2 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.SpearsAsTribute, points: 3 },
      { trait: UnitTraits.Steadfast, points: 1 },
    ],
  }),
  WarriorsFormedArchers: UnitProfile.fromObject({
    type: UnitTypes.Warriors,
    name: 'Formed Archers',
    points: 21,
    combatDice: 8,
    shootingDice: 8,
    armour: 2,
    stamina: 4,
    traitsLimit: 5,
    options: [
      { id: 1, name: 'Increase Armour to 3', points: 5, modifiers: { armour: 1 } },
      {
        id: 2,
        name: 'Exchange Bow for Short Bow',
        points: -1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 3,
        name: 'Exchange Bow for Elf Bow/ Long Bow/ Crossbow:',
        points: 1,
        modifiers: { missileType: MissileTypes.ElfBowOrCrossbowOrLongbow },
      },
    ],
    missileType: MissileTypes.BowOrMountedElfBow,
    availableTraits: [
      { trait: UnitTraits.Brittle, points: -1 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Relentless, points: 2 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.Steadfast, points: 1 },
    ],
  }),
  WarriorsHordes: UnitProfile.fromObject({
    type: UnitTypes.Warriors,
    name: 'Hordes',
    points: 12,
    combatDice: 8,
    shootingDice: 0,
    armour: 2,
    stamina: 4,
    traitsLimit: 5,
    options: [],
    availableTraits: [
      { trait: UnitTraits.Amphibious, points: 1 },
      { trait: UnitTraits.Brittle, points: -1 },
      { trait: UnitTraits.Fearsome, points: 1 },
      { trait: UnitTraits.Impetuous, points: 0 },
      { trait: UnitTraits.Relentless, points: 2 },
      { trait: UnitTraits.Reluctant, points: -2 },
    ],
  }),
  SkirmishersShooters: UnitProfile.fromObject({
    type: UnitTypes.Skirmishers,
    name: 'Shooters',
    points: 10,
    combatDice: 6,
    shootingDice: 6,
    armour: 2,
    armourWhenShot: 3,
    stamina: 2,
    traitsLimit: 5,
    builtInTraits: [UnitTraits.Agile, UnitTraits.Evade],
    missileType: MissileTypes.Javelins,
    options: [
      {
        id: 1,
        name: 'Remove Javelin and reduce Shooting Dice to 0. No other missiles can be taken',
        points: -2,
        modifiers: { shootingDice: -6, missileType: MissileTypes.None },
      },
      {
        id: 2,
        name: 'Exchange Javelin for Short Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 3,
        name: 'Exchange Javelin for Bow or Sling',
        points: 2,
        modifiers: { missileType: MissileTypes.BowOrSling },
      },
      {
        id: 4,
        name: 'Exchange Javelin for Elf Bow/ Long Bow/ Crossbow',
        points: 3,
        modifiers: { missileType: MissileTypes.ElfBowOrCrossbowOrLongbow },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.Amphibious, points: 1 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Flying, points: 10 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
    ],
  }),
  SkirmishersLightInfantry: UnitProfile.fromObject({
    type: UnitTypes.Skirmishers,
    name: 'Light Infantry',
    points: 14,
    combatDice: 8,
    shootingDice: 4,
    armour: 3,
    stamina: 2,
    traitsLimit: 5,
    builtInTraits: [UnitTraits.Agile, UnitTraits.Evade],
    missileType: MissileTypes.Javelins,
    options: [
      {
        id: 1,
        name: 'Remove Javelin and reduce Shooting Dice to 0. No other missiles can be taken',
        points: -2,
        modifiers: { shootingDice: -4, missileType: MissileTypes.None },
      },
      {
        id: 2,
        name: 'Exchange Javelin for Short Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 3,
        name: 'Exchange Javelin for Bow or Sling',
        points: 2,
        modifiers: { missileType: MissileTypes.BowOrMountedElfBow },
      },
      {
        id: 4,
        name: 'Exchange Javelin for Elf Bow/ Long Bow/ Crossbow',
        points: 3,
        modifiers: { missileType: MissileTypes.ElfBowOrCrossbowOrLongbow },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.Amphibious, points: 1 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Flying, points: 10 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Relentless, points: 1 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.SpearsAsTribute, points: 3 },
    ],
  }),
  HeavyRidersKnights: UnitProfile.fromObject({
    type: UnitTypes.HeavyRiders,
    name: 'Knights',
    points: 26,
    combatDice: 10,
    shootingDice: 0,
    armour: 4,
    stamina: 3,
    traitsLimit: 5,
    options: [],
    builtInTraits: [
      UnitTraits.CounterCharge,
      UnitTraits.Disengage,
      UnitTraits.Fearsome,
      UnitTraits.ThunderousCharge,
    ],
    availableTraits: [
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Impetuous, points: 0 },
      { trait: UnitTraits.Relentless, points: 1 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.SpearsAsTribute, points: 3 },
    ],
  }),
  HeavyRidersMediumCavalry: UnitProfile.fromObject({
    type: UnitTypes.HeavyRiders,
    name: 'Medium Cavalry',
    points: 20,
    combatDice: 10,
    shootingDice: 5,
    armour: 3,
    stamina: 3,
    traitsLimit: 5,
    missileType: MissileTypes.Javelins,
    builtInTraits: [UnitTraits.CounterCharge, UnitTraits.Disengage],
    options: [
      {
        id: 1,
        name: 'Remove Javelin and reduce Shooting Dice to 0. No other missiles can be taken',
        points: -2,
        modifiers: { shootingDice: -5, missileType: MissileTypes.None },
      },
      {
        id: 2,
        name: 'Exchange Javelin for Mounted Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 3,
        name: 'Exchange Javelin for Mounted Elf Bow',
        points: 2,
        modifiers: { missileType: MissileTypes.BowOrMountedElfBow },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Fearsome, points: 3 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Impetuous, points: 0 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Relentless, points: 1 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.SpearsAsTribute, points: 3 },
    ],
  }),
  LightRidersScouts: UnitProfile.fromObject({
    type: UnitTypes.LightRiders,
    name: 'Scouts',
    points: 17,
    combatDice: 6,
    shootingDice: 6,
    armour: 3,
    stamina: 2,
    traitsLimit: 5,
    missileType: MissileTypes.Javelins,
    builtInTraits: [UnitTraits.CounterCharge, UnitTraits.Disengage, UnitTraits.Evade],
    options: [
      { id: 1, name: 'Reduce Armour to 2', points: -3, modifiers: { armour: -1 } },
      {
        id: 2,
        name: 'Remove Javelin and reduce Shooting Dice to 0. No other missiles can be taken',
        points: -2,
        modifiers: { shootingDice: -6, missileType: MissileTypes.None },
      },
      {
        id: 3,
        name: 'Exchange Javelin for Mounted Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 4,
        name: 'Exchange Javelin for Mounted Elf Bow',
        points: 2,
        modifiers: { missileType: MissileTypes.BowOrMountedElfBow },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Flying, points: 10 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Relentless, points: 1 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
    ],
  }),
  LightRidersNobleRidersAndLightChariots: UnitProfile.fromObject({
    type: UnitTypes.LightRiders,
    name: 'Noble Riders & Light Chariots',
    points: 18,
    combatDice: 8,
    shootingDice: 4,
    armour: 3,
    stamina: 2,
    traitsLimit: 5,
    missileType: MissileTypes.Javelins,
    builtInTraits: [UnitTraits.CounterCharge, UnitTraits.Disengage, UnitTraits.Evade],
    options: [
      { id: 1, name: 'Increase Armour to 4', points: 3, modifiers: { armour: 1 } },
      {
        id: 2,
        name: 'Remove Javelin and reduce Shooting Dice to 0. No other missiles can be taken',
        points: -2,
        modifiers: { shootingDice: -4, missileType: MissileTypes.None },
      },
      {
        id: 3,
        name: 'Exchange Javelin for Mounted Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
      {
        id: 4,
        name: 'Exchange Javelin for Mounted Elf Bow',
        points: 2,
        modifiers: { missileType: MissileTypes.BowOrMountedElfBow },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.Drilled, points: 2 },
      { trait: UnitTraits.Fearsome, points: 3 },
      { trait: UnitTraits.Flying, points: 10 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Impetuous, points: 0 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Relentless, points: 1 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Replacements, points: 2 },
      { trait: UnitTraits.SpearsAsTribute, points: 3 },
    ],
  }),
  MonstrositiesGiant: UnitProfile.fromObject({
    type: UnitTypes.Monstrosities,
    name: 'Giant',
    points: 42,
    combatDice: 10,
    shootingDice: 5,
    armour: 4,
    stamina: 3,
    traitsLimit: 10,
    missileType: MissileTypes.Boulders,
    builtInTraits: [
      UnitTraits.Aloof,
      UnitTraits.Brutal,
      UnitTraits.Fearsome,
      UnitTraits.Impetuous,
      UnitTraits.Steadfast,
      UnitTraits.Towering,
    ],
    options: [
      { id: 1, name: 'Increase Armour to 5', points: 8, modifiers: { armour: 1 } },
      {
        id: 2,
        name: 'Remove Boulders and reduce Shooting Dice to 0 but increase Combat Dice to 12',
        points: 0,
        modifiers: { shootingDice: -5, combatDice: 2, missileType: MissileTypes.None },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Relentless, points: 4 },
      { trait: UnitTraits.Reluctant, points: -2 },
    ],
  }),
  MonstrositiesElephantsAndWarMammoths: UnitProfile.fromObject({
    type: UnitTypes.Monstrosities,
    name: 'Elephants & War Mammoths',
    points: 40,
    combatDice: 10,
    shootingDice: 5,
    armour: 4,
    stamina: 3,
    traitsLimit: 10,
    missileType: MissileTypes.Javelins,
    builtInTraits: [
      UnitTraits.Aloof,
      UnitTraits.Brutal,
      UnitTraits.CounterCharge,
      UnitTraits.Fearsome,
      UnitTraits.Impetuous,
      UnitTraits.Stampede,
      UnitTraits.Steadfast,
      UnitTraits.Towering,
    ],
    options: [
      { id: 1, name: 'Increase Armour to 5', points: 8, modifiers: { armour: 1 } },
      {
        id: 2,
        name: 'Remove Javelins and reduce Shooting Dice to 0. No further missiles can be taken',
        points: -2,
        modifiers: { shootingDice: -5, missileType: MissileTypes.None },
      },
      {
        id: 3,
        name: 'Exchange Javelins for Mounted Bow',
        points: 1,
        modifiers: { missileType: MissileTypes.ShortOrMountedBow },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.HelsBreath, points: 2 },
      { trait: UnitTraits.Marksman },
      { trait: UnitTraits.Relentless, points: 4 },
      { trait: UnitTraits.Reluctant, points: -2 },
    ],
  }),
  MonstrositiesDragon: UnitProfile.fromObject({
    type: UnitTypes.Monstrosities,
    name: 'Dragon',
    points: 55,
    combatDice: 10,
    shootingDice: 10,
    armour: 4,
    stamina: 3,
    traitsLimit: 10,
    missileType: MissileTypes.DragonsBreath,
    builtInTraits: [
      UnitTraits.Aloof,
      UnitTraits.Blast,
      UnitTraits.Brutal,
      UnitTraits.Fearsome,
      UnitTraits.HelsBreath,
      UnitTraits.Impetuous,
      UnitTraits.Steadfast,
      UnitTraits.Towering,
    ],
    options: [
      { id: 1, name: 'Increase Armour to 5', points: 8, modifiers: { armour: 1 } },
      {
        id: 2,
        name: "Remove Dragon's Breath and reduce Shooting Dice to 0 and remove Blast and Hel's Breath Traits",
        points: -10,
        modifiers: {
          shootingDice: -10,
          missileType: MissileTypes.None,
          discards: [UnitTraits.Blast.name, UnitTraits.HelsBreath.name],
        },
      },
    ],
    availableTraits: [
      { trait: UnitTraits.Amphibious, points: 3 },
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.Flying, points: 15 },
      { trait: UnitTraits.Reluctant, points: -2 },
    ],
  }),
  MonstrositiesFlyingBeast: UnitProfile.fromObject({
    type: UnitTypes.Monstrosities,
    name: 'Flying Beast',
    points: 30,
    combatDice: 10,
    shootingDice: 0,
    armour: 3,
    stamina: 2,
    traitsLimit: 10,
    builtInTraits: [UnitTraits.Aloof, UnitTraits.Big, UnitTraits.Fearsome, UnitTraits.Flying],
    options: [
      { id: 1, name: 'Increase Armour to 4', points: 8, modifiers: { armour: 1 } },
      { id: 2, name: 'Increase Stamina to 3', points: 8, modifiers: { stamina: 1 } },
    ],
    availableTraits: [
      { trait: UnitTraits.AuraOfDread, points: 12 },
      { trait: UnitTraits.Brutal, points: 14 },
      { trait: UnitTraits.Reluctant, points: -2 },
      { trait: UnitTraits.Towering, points: 2 },
    ],
  }),
  MonstrositiesArtillery: UnitProfile.fromObject({
    type: UnitTypes.Monstrosities,
    name: 'Artillery',
    points: 20,
    combatDice: 6,
    shootingDice: 6,
    armour: 3,
    stamina: 2,
    traitsLimit: 10,
    missileType: MissileTypes.LightArtillery,
    builtInTraits: [
      UnitTraits.Aloof,
      UnitTraits.Blast,
      UnitTraits.Fixed,
      UnitTraits.HelsBreath,
      UnitTraits.Reluctant,
      UnitTraits.Slow,
    ],
    options: [
      { id: 1, name: 'Increase Armour to 4', points: 2, modifiers: { armour: 1 } },
      {
        id: 2,
        name: 'Exchange Light Artillery for Heavy Artillery and increase Combat and Shooting Dice to 8',
        points: 8,
        modifiers: { combatDice: 2, shootingDice: 2, missileType: MissileTypes.HeavyArtillery },
      },
    ],
    availableTraits: [],
  }),
}

export default UnitProfiles
